// Generated by CoffeeScript 1.3.3

/*
# Copyright (c) 2012 - <mlunzena@uos.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
*/


/*
***************************************************************************
* BOOTSTRAP
***************************************************************************
*/


/*
Initialize the router and start Backbone hash listening magic
*/


(function() {

  $(document).ready(function() {
    /*
      As the webpage contains the initial USER data (id and name),
      pre-populate the global $Session (the initial $ indicates a global
      variable) with these. This way we spare us an initial AJAX call.
    */
    window.$Session = new SessionModel(USER);
    /*
      Declare the global $App object (the initial $ indicates a global
      variable). We need it to dynamically navigate between routes etc.
    */

    window.$App = new AppRouter();
    return Backbone.history.start();
  });

}).call(this);
